name: Clean up blob directory

description: Only save the 3 most recent models

inputs:

  connection-string:
    description: Required to auth blob commands
    required: true

  container-name:
    description: Name of container where models are stored
    required: true

  branch-name:
    description: Name of the current branch
    required: true

  max-saved-models:
    description: Maximum number of models saved on blob
    required: true

runs:
  using: "node12"
  main: "index.js"
