name: Train Rasa Chatbot and Upload Artifacts to Azure Blob
on:

  pull_request:
    types: [closed]
    branches:
      - master
env:
  AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZ_STORAGE_ACC_CONN_STRING }}
  CHATBOT_MODEL_NAME: ${{ github.event.repository.name }}-PR-${{ github.event.pull_request.number }}-1-job
jobs:
  rasa-train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2

      - name: Rasa train
        uses: RasaHQ/rasa-train-test-gha@main
        with:
          rasa_version: latest-full
          publish_summary: false
          rasa_test: false
          train_args: --fixed-model-name ${{ env.CHATBOT_MODEL_NAME }}
          configuration: config.yml
          
      - name: Where did the chatbot go?
        shell: bash
        run: |
          echo "pwd" && pwd
          echo "------"
          echo "ls -la" && ls -la
          echo "------"
          echo "cd ${{ github.workspace }}/models" && cd ${{ github.workspace }}/models
          echo "------"
          echo "pwd" && pwd
          echo "------"
          echo "ls -la" && ls -la
          
      - name: Upload Chatbot Artifact to GitHub
        uses: actions/upload-artifact@v2.2.3
        with:
          name: ${{ env.CHATBOT_MODEL_NAME }}.tar.gz
          path: ${{ github.workspace }}/models/${{ env.CHATBOT_MODEL_NAME }}.tar.gz
          if-no-files-found: error
          retention-days: 1
          
      - name: Upload chatbot artifact to Azure container
        shell: bash
        run: |
          az storage blob upload \
          -c chatbot \
          -f ${{ github.workspace }}/models/${{ env.CHATBOT_MODEL_NAME }}.tar.gz \
          -n ${{ github.event.repository.name }}/${{ env.CHATBOT_MODEL_NAME }}.tar.gz
