name: Azure Blob digging
on:
  workflow_dispatch:

jobs:
  rasa-train-and-upload:
    runs-on: ubuntu-latest
    env:
      STORAGE_ACC_NAME: storageaccpow
      AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZ_STORAGE_ACC_CONN_STRING }}
      
    steps:
          
      - name: Checkout master branch
        uses: actions/checkout@v2

      - name: List blobs in container
        shell: bash
        run: |- 
          az storage blob list -c chatbot --prefix ${{ github.event.repository.name }}/ --query "[].[name, properties.creationTime]" -o json
