# This is a basic workflow to help you get started with Actions

name: Train Rasa Chatbot and Upload Artifacts to Azure Blob

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  rasa-train:
    runs-on: ubuntu-latest
    steps:
#       - name: Checkout master branch
#         uses: actions/checkout@v2

#       - name: Rasa Train
#         uses: RasaHQ/rasa-train-test-gha@main
#         with:
#           publish_summary: false
#           rasa_test: false
          
        - name: Azure Login
          run: 
            az login --service-principal --username ${{ secrets.AZ_SP_APP_ID }} --password ${{ secrets.AZ_SP_PWD }} --tenant ${{secrets.AZ_SP_TENANT_ID }}
          
        - name: Azure CLI Container Creation
          uses: azure/CLI@v1
          with:
            inlineScript: |
              az storage container create -n chatbot --account-name storageaccpow --account-key ${{ secrets.AZ_STORAGE_ACC_KEY }} --fail-on-exist
