# This is a basic workflow to help you get started with Actions

name: Train Rasa Chatbot and Upload Artifacts to Azure Blob

# Controls when the action will run. 
on:

  pull_request:
    types: [closed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  rasa-train-and-upload:
    runs-on: ubuntu-latest
    env:
      STORAGE_ACC_NAME: storageaccpow
      AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZ_STORAGE_ACC_CONN_STRING }}
      CHATBOT_MODEL_NAME: ${{ github.event.repository.name }}-${{ githb.event.pull_request.number }}
      
    steps:
      - name: Event what?
        shell: bash
        run: |-
          echo "Event Name -> "${{ github.event_name }} 
          echo "Event Action -> "${{ github.event.action }} 
          echo "Pull Request Merged -> "${{github.event.pull_request.merged }}
          
      - name: Checkout master branch
        uses: actions/checkout@v2
      
        
      - name: Rasa Train
        uses: RasaHQ/rasa-train-test-gha@main
        with:
          publish_summary: false
          rasa_test: false
          train_args: --fixed-model-name ${{ env.CHATBOT_MODEL_NAME }}
       
      - name: az Upload Chatbot Artifact
        if: ${{ always() }}
        shell: bash
        run: |-
          az extension add --name storage-preview
          az storage blob upload -c chatbot -f ${{ github.workspace }}/models/${{ env.CHATBOT_MODEL_NAME }}.tar.gz -n ${{ github.event.repository.name }}/${{ env.CHATBOT_MODEL_NAME }}.tar.gz 
