# This is a basic workflow to help you get started with Actions

name: Train Rasa Chatbot and Upload Artifacts to Azure Blob

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  rasa-train-and-upload:
    if: github.even_name == 'pull_request' && github.evet.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      MODEL_NAME: ${{ github.event.repository.name }}-
      STORAGE_ACC_NAME: storageaccpow
      
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2

      - name: Rasa Train
        uses: RasaHQ/rasa-train-test-gha@main
        with:
          publish_summary: false
          rasa_test: false
          train_args: --fixed-model-name ${{ env.MODEL_NAME }}
       
      - name: Azure Login
        shell: bash
        run: 
          az login --service-principal --username ${{ secrets.AZ_SP_APP_ID }} --password ${{ secrets.AZ_SP_PWD }} --tenant ${{secrets.AZ_SP_TENANT_ID }}

#       - name: az Container Creation
#         uses: azure/CLI@v1
#         with:
#           inlineScript: |
#             az storage container create -n chatbot --account-name ${{ env.STORAGE_ACC_NAME }} --account-key ${{ secrets.AZ_STORAGE_ACC_KEY }} --fail-on-exist

      - name: az Upload Chatbot Artifact
        if: ${{ always() }}
        shell: bash
        run: |-
          az extension add --name storage-preview
          az storage blob upload -c chatbot -f ${{ github.workspace }}/models/${{ env.MODEL_NAME }}.tar.gz -n ${{ github.event.repository.name }}/${{ env.MODEL_NAME }}.tar.gz --account-name ${{ env.STORAGE_ACC_NAME }} --account-key ${{ secrets.AZ_STORAGE_ACC_KEY }}
