name: Train Rasa Chatbot and Upload Artifacts to Azure Blob
on:

  pull_request:
    types: [closed]
    branches:
      - master
env:
  AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZ_STORAGE_ACC_CONN_STRING }}
  CHATBOT_MODEL_NAME: ${{ github.event.repository.name }}-PR-${{ github.event.pull_request.number }}-2-jobs
jobs:
  rasa-train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2

      - name: Rasa train
        uses: RasaHQ/rasa-train-test-gha@main
        with:
          publish_summary: false
          rasa_test: false
          train_args: --fixed-model-name ${{ env.CHATBOT_MODEL_NAME }}
      
      - name: Where did the chatbot go?
        shell: bash
        run: |
          pwd
          echo "------"
          ls -la
          echo "------"
          cd ${{ github.workspace }}/models
          echo "------"
          pwd
          echo "------"
          ls -la
      
#       - name: Upload Chatbot Artifact to GitHub
#         uses: actions/upload-artifact@v2.2.3
#         with:
#           name: ${{ env.CHATBOT_MODEL_NAME }}.tar.gz
#           path: ${{ github.workspace }}/models/${{ env.CHATBOT_MODEL_NAME }}.tar.gz
#           if-no-files-found: error
#           retention-days: 1
          
#   blob-upload:
#     runs-on: ubuntu-latest
#     needs: rasa-train
#     env:
#       AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZ_STORAGE_ACC_CONN_STRING }}
#       CHATBOT_MODEL_NAME: ${{ github.event.repository.name }}-PR#${{ github.event.pull_request.number }}
#     steps:
#       - name: Download Chatbot Artifact from GitHub
#         uses: actions/download-artifact@v2
#         with:
#           name: ${{ env.CHATBOT_MODEL_NAME }}
          
#       - name: Upload chatbot artifact to Azure container
#         shell: bash
#         run: |
#           az storage blob upload \
#           -c chatbot \
#           -f ./${{ env.CHATBOT_MODEL_NAME }}.tar.gz \
#           -n ${{ github.event.repository.name }}/${{ env.CHATBOT_MODEL_NAME }}.tar.gz
