# This is a basic workflow to help you get started with Actions

name: Train Rasa Chatbot and Upload Artifacts to Azure Blob

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
#   push:
#     branches: [ develop ]
  pull_request:
    types: [closed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  rasa-train-and-upload:
#     if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      STORAGE_ACC_NAME: storageaccpow
      
    steps:
      - name: Event what?
        shell: bash
        run: |-
          echo ${{ github.event_name }} ${{ github.event.action }} ${{github.event.pull_request.merged }}
      - name: Checkout master branch
        uses: actions/checkout@v2
        
      - name: Get PR Number
        run: echo "PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")" >> $GITHUB_ENV
        
      - name: Rasa Train
        uses: RasaHQ/rasa-train-test-gha@main
        with:
          publish_summary: false
          rasa_test: false
          train_args: --fixed-model-name ${{ github.actor }}-${{ env.TIMESTAMP }}
       
      - name: Azure Login
        shell: bash
        run: 
          az login --service-principal --username ${{ secrets.AZ_SP_APP_ID }} --password ${{ secrets.AZ_SP_PWD }} --tenant ${{secrets.AZ_SP_TENANT_ID }}

      - name: az Upload Chatbot Artifact
        if: ${{ always() }}
        shell: bash
        run: |-
          az extension add --name storage-preview
          az storage blob upload -c chatbot -f ${{ github.workspace }}/models/${{ github.actor }}-${{ env.TIMESTAMP }}.tar.gz -n ${{ github.event.repository.name }}/${{ github.actor }}-${{ env.TIMESTAMP }}.tar.gz --account-name ${{ env.STORAGE_ACC_NAME }} --account-key ${{ secrets.AZ_STORAGE_ACC_KEY }}
