name: Train Rasa Chatbot and Upload Artifacts to Azure Blob
on:

  pull_request:
    types: [closed]
    branches:
      - develop

  workflow_dispatch:

jobs:
  rasa-train-and-upload:
    runs-on: ubuntu-latest
    env:
      AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZ_STORAGE_ACC_CONN_STRING }}
      CHATBOT_MODEL_NAME: ${{ github.event.repository.name }}-${{ github.event.pull_request.number }}
      
    steps:
          
      - name: Checkout master branch
        uses: actions/checkout@v2
      
        
      - name: Rasa Train
        uses: RasaHQ/rasa-train-test-gha@main
        with:
          publish_summary: false
          rasa_test: false
          train_args: --fixed-model-name ${{ env.CHATBOT_MODEL_NAME }}
       
      - name: az Upload Chatbot Artifact
        shell: bash
        run: |
          az storage blob upload \
          -c chatbot \
          -f ${{ github.workspace }}/models/${{ env.CHATBOT_MODEL_NAME }}.tar.gz \
          -n ${{ github.event.repository.name }}/${{ env.CHATBOT_MODEL_NAME }}.tar.gz a
